Top Section UI
pdybowski/booking-clone-Web pull request #25
Opened 2021-03-20 14:50 UTC by ibednorz

I don't know how to change the color of the loading wheel

2021-03-20 17:17 UTC, GoraJakub commented
what is happening? 😄

![image](https://user-images.githubusercontent.com/74857860/111878214-8347da00-89a7-11eb-98bc-a5c5c46ea9c7.png)

Also I would change 'forgot password' to normal text link rather than that fancy button, on the other hand login button should looks like that XD Moreover I would move register button next to the login button and add a little margin between inputs but that's all @pdybowskis decisions

![image](https://user-images.githubusercontent.com/74857860/111878963-049f6c80-89a8-11eb-9310-86d7c24a2e20.png)

2021-03-20 21:43 UTC, pdybowski commented
Kuba is right. Please move register next to the login button
'forgot password' should be anchor tag - plain text
'register' can be a button

2021-03-20 21:44 UTC, pdybowski requested changes
check comments and fix it ASAP

2021-03-21 12:21 UTC, hoolek77 approved these changes

2021-03-21 12:21 UTC, GoraJakub approved these changes

2021-03-21 13:00 UTC, merged